#!/usr/bin/env sh
set -e

initialStuff() {
    php artisan migrate --force --no-ansi -q; \
    php artisan storage:link; \
    php artisan icons:cache; \
    php artisan event:cache; \
    php artisan config:cache; \
    php artisan view:cache; \
    php artisan route:cache; \
    php artisan filament:cache-components; \
    php artisan filament:upgrade; \
    php artisan optimize; \
    php artisan optimize:clear;
}

if [ "$1" != "" ]; then
    exec "$@"
else
    initialStuff
    echo "Octane Server: Swoole"
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.swoole.conf
fi
